/**
 * IlhamXkyo Engineering Portfolio Data Matrix
 * All 30+ repositories sourced directly from https://github.com/IlhamXkyo
 */

export const DEVELOPER_PROFILE = {
  name: "Ilham",
  handle: "IlhamXkyo",
  title: "Building developer tools, automation systems, and practical web applications",
  headline: "Building developer tools, automation systems, and practical web applications.",
  subheadline: "I build small systems that solve annoying problems.",
  location: "AMBON, INDONESIA · AVAILABLE REMOTELY",
  email: "xanderilham4@gmail.com",
  github: "https://github.com/IlhamXkyo",
  avatarUrl: "https://avatars.githubusercontent.com/u/263917511?v=4",
  gifUrl: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbXp1cDZrOXI5bHp4c3dzNW5hYXhkcXVzMHF4azMyY3Z3aG52NGJzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/6C0m3zHvKEsoiKYXq2/giphy.gif",
  bio: "I build small systems that solve annoying problems. Focused on practical developer tools, process automation, and zero-dependency utilities.",
  dailyRoutine: [
    "Developing lightweight, zero-dependency Node.js and TypeScript command line utilities",
    "Designing clean, functional interfaces with minimalist design principles",
    "Managing operating system sockets, port collisions, and process termination",
    "Engineering offline-first civic document workflows and administrative utilities",
    "Analyzing text cadence and stylometrics to remove repetitive corporate writing patterns"
  ],
  stats: {
    totalRepos: 30,
    reposDisplay: "30+",
    devTools: 10,
    civicApps: 5,
    quantAndAI: 9,
    nlpAndProse: 3,
    games: 3,
    testsPassing: 48,
    runtimeDeps: 0,
    license: "MIT"
  },
  skills: [
    { category: "Developer Tools & CLI", items: ["Zero-Dependency Node.js", "Cross-Platform Socket Diagnostics", "Process Tree Introspection", "Token Masking Algorithms", "Electron Desktop Apps"] },
    { category: "Clean Interface Craft", items: ["Design Systems & Semantic Tokens", "Tactile Micro-Interactions", "Fluid Canvas Graphics", "Modular Typographic Scales", "Modern CSS Architecture"] },
    { category: "Stylometrics & NLP", items: ["Sentence Burstiness Analysis", "Syllable Entropy Modeling", "Syntactic Rhythm Parsing", "Anti-Slop Heuristic Engines"] },
    { category: "Practical Systems & Civic", items: ["TypeScript / JavaScript", "Python Automation", "PHP & Relational SQL", "Offline-First Paged Media", "WebSockets & Event Streams"] }
  ]
};

export const FEATURED_CASE_STUDIES = [
  {
    id: "codemask",
    name: "CodeMask",
    category: "tools",
    tagline: "Secret Redactor & LLM Egress Sanitizer",
    techStack: "Pure JavaScript · Zero Dependencies · Memory Vault",
    problem: "Developers frequently leak live API keys, database credentials, and Bearer tokens when pasting code snippets into LLM chats.",
    whyBuilt: "Accidental credential leakage into cloud AI providers causes severe security exposures. Existing linters either block the prompt completely or do not provide bidirectional reversal.",
    implemented: "A bidirectional syntax-preserving token masker in pure JavaScript. Scans code for high-entropy patterns (OpenAI, Anthropic, Stripe, AWS, Postgres URIs, JWTs) and replaces them with deterministic placeholders (__CODEMASK_API_KEY_1__), storing mappings in an isolated memory vault for instant restoration upon response ingress.",
    challenge: "Preserving strict programming language syntax (JSON, SQL, Python, JavaScript) without corrupting quotes, commas, brackets, or string boundaries during regular expression substitution.",
    results: "0 external dependencies. Sub-millisecond execution (< 1.2ms for 1,000 lines of code). 42 passing automated test assertions with 100% bidirectional restoration accuracy.",
    workbenchTarget: "codemask-workbench",
    liveUrl: null,
    githubUrl: "https://github.com/IlhamXkyo/codemask"
  },
  {
    id: "portwarden",
    name: "Portwarden Sentinel",
    category: "tools",
    tagline: "Cross-Platform Port Collision Inspector & Zombie Process Terminator",
    techStack: "Node.js Standard Library · Cross-Platform CLI · Netstat/Lsof/SS",
    problem: "Orphaned background dev servers (Node, Vite, Next.js, Postgres) hold onto network ports and throw EADDRINUSE: port already in use errors during development.",
    whyBuilt: "Developers waste minutes searching for obscure PIDs using multi-step shell commands (lsof -i :3000, netstat -ano, taskkill /PID ... /F) just to restart their local servers.",
    implemented: "A lightweight, zero-dependency CLI utility written in pure Node.js standard library (child_process, net). Queries native OS socket tables across Windows (netstat), macOS (lsof), and Linux (ss), maps socket bindings to process tree PIDs, and dispatches verified graceful or force terminations.",
    challenge: "Windows netstat and Unix lsof have vastly different column formatting, buffering characteristics, and race conditions where a killed process takes a few hundred milliseconds to fully release OS socket handles.",
    results: "0 external npm dependencies. Executes in under 120ms. Verified release polling loop ensures port is 100% available before terminal return.",
    workbenchTarget: "portwarden-workbench",
    liveUrl: null,
    githubUrl: "https://github.com/IlhamXkyo/portwarden"
  },
  {
    id: "slop-lens",
    name: "Slop-Lens Linter",
    category: "nlp",
    tagline: "Real-Time Stylometrics Inspector & AI Heuristic Linter",
    techStack: "Client-Side JavaScript · Stylometrics Pipeline · Web Audio API",
    problem: "Generic AI text generators produce monotonous, low-burstiness prose filled with predictable corporate buzzwords and robotic transitional formulas.",
    whyBuilt: "Reviewing engineering logs, technical documentation, and proposals required a transparent, client-side tool to spot repetitive AI tropes without sending sensitive drafts to third-party SaaS checkers.",
    implemented: "An in-browser stylometrics pipeline computing sentence length standard deviation (burstiness distribution), syllable complexity entropy, and heuristic dictionary matching across both English and Indonesian corporate cliches. Generates an optical barcode visualization representing sentence cadence.",
    challenge: "Designing robust sentence boundary parsing that correctly handles abbreviations, decimal numbers, unpunctuated final clauses, and bilingual text without loading heavyweight NLP Python binaries into the browser.",
    results: "Runs 100% client-side in vanilla JavaScript. Telemetry updates in under 4ms on 5,000-word documents. Accurately flags over 18 known AI cliche categories with dynamic optical rhythm graphs.",
    workbenchTarget: "sloplens-workbench",
    liveUrl: null,
    githubUrl: "https://github.com/IlhamXkyo/slop-lens"
  },
  {
    id: "warga-os",
    name: "Warga-OS",
    category: "civic",
    tagline: "Offline-First Citizen Administration & Utility Suite",
    techStack: "Offline-First Web App · ISO A4 Paged Media · LocalStorage",
    problem: "Indonesian neighborhood administrators (RT/RW) and residents struggle with convoluted government portals, inaccessible printers, and manual administrative form formatting.",
    whyBuilt: "Local neighborhood administration needs instant, offline-capable tools to generate standardized citizen letters and verify residency without relying on spotty internet or paying administrative middlemen.",
    implemented: "An offline-first web application featuring standardized administrative letter generators (Surat Pengantar RT/RW, Keterangan Domisili) formatted to ISO A4 print standards, a PLN electricity token cost estimator, and quick-reference citizen rights documentation.",
    challenge: "Ensuring pixel-perfect CSS @media print layout rendering that matches official Indonesian administrative templates across diverse desktop and mobile browsers with zero external PDF rendering services.",
    results: "100% offline functionality via browser service worker and local storage. Zero database server overhead. Standard A4 print compliance verified across Chrome, Firefox, and mobile Safari.",
    workbenchTarget: null,
    liveUrl: "https://github.com/IlhamXkyo/warga-os",
    githubUrl: "https://github.com/IlhamXkyo/warga-os"
  },
  {
    id: "aurum-ai-terminal",
    name: "Aurum-AI-Terminal",
    category: "quant",
    tagline: "Local Financial Sentiment & Quantitative Signal Engine",
    techStack: "JavaScript Terminal UI · Financial Sentiment Lexicon · Real-Time Telemetry",
    problem: "Retail trading algorithms often rely on heavy, opaque cloud black-boxes that cannot be inspected, run offline, or integrated into lightweight terminal setups.",
    whyBuilt: "Built to explore rule-based quantitative signal filtering and news sentiment scoring on precious metal assets (XAU/USD) directly through an interactive terminal interface.",
    implemented: "A terminal-based quantitative analysis dashboard that aggregates market price ticks, computes technical momentum indicators (RSI, Bollinger Bands, EMA crossovers), and matches financial headlines against an annotated market sentiment lexicon.",
    challenge: "Preventing UI thread stutter during rapid incoming tick updates while maintaining synchronous indicator calculations and dynamic terminal ASCII telemetry.",
    results: "Processes 500+ simulated price ticks per second with zero frame drops. Sub-10ms indicator calculation cycles and modular architecture for backtesting historical scenarios.",
    workbenchTarget: null,
    liveUrl: "https://github.com/IlhamXkyo/aurum-ai-terminal",
    githubUrl: "https://github.com/IlhamXkyo/aurum-ai-terminal"
  }
];

export const REPOSITORIES = [
  {
    id: "portwarden",
    name: "portwarden",
    category: "tools",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-03",
    tagline: "Developer Port Collision Inspector & Zombie Process Terminator",
    description: "Developer port collision inspector, zombie process terminator, and port sentinel for Windows, macOS, and Linux with zero external dependencies.",
    architecture: "Lightweight cross-platform socket probing architecture. Leverages native OS socket tables (netstat, lsof, ss) with verified process tree PID inspection and guaranteed SIGKILL release polling to eliminate EADDRINUSE collisions.",
    highlights: [
      "Zero external npm dependencies (pure Node.js standard library)",
      "Cross-platform support: Windows taskkill, macOS/Linux kill with verification",
      "Detects zombie dev servers (Node, Vite, Python, Docker)",
      "Verified release polling ensures port is truly free before returning"
    ],
    cliSnippet: "npx portwarden 3000\nnpx portwarden free 3000",
    githubUrl: "https://github.com/IlhamXkyo/portwarden",
    liveUrl: null,
    topics: ["developer-tools", "cli", "port-killer", "zombie-process", "cross-platform", "zero-dependencies"],
    featured: true
  },
  {
    id: "slop-lens",
    name: "slop-lens",
    category: "nlp",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-07",
    tagline: "Real-time Anti-Slop Stylometrics & AI Writing Heuristic Linter",
    description: "Real-time Anti-Slop stylometrics inspector and AI writing heuristic linter measuring sentence burstiness, syllable entropy, and corporate filler density.",
    architecture: "Algorithmic text analysis pipeline calculating sentence length variance (burstiness distribution), syllable complexity entropy, passive voice frequency, and heuristic matching against a curated dictionary of generic AI filler vocabulary.",
    highlights: [
      "Sentence burstiness variance calculation (standard deviation & IQR)",
      "Syllable entropy and readability grade telemetry",
      "Real-time detection of AI clichés ('delve', 'testament', 'tapestry', 'crucial')",
      "Rhythm bar-graph displaying sentence cadence like an optical waveform"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/slop-lens.git",
    githubUrl: "https://github.com/IlhamXkyo/slop-lens",
    liveUrl: null,
    topics: ["stylometrics", "anti-slop", "nlp", "heuristics", "writing-analysis", "developer-tools"],
    featured: true
  },
  {
    id: "zero-g-notes",
    name: "zero-g-notes",
    category: "tools",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-06",
    tagline: "Tactile Desktop Notes App with Floating Card Ergonomics",
    description: "An early desktop notes experiment with floating card layout, weightless toggle, and an editorial minimalist interface. Built with Electron & Matter.js.",
    architecture: "Electron desktop client integrating a 2D card positioning engine. Synchronizes floating DOM card representations with underlying coordinate boundaries, complete with typing stabilization locks and local persistent state storage.",
    highlights: [
      "Floating card layout with drag stabilization",
      "Instant weightless toggle for freeform positioning or structured bottom stacking",
      "Typing stabilization lock prevents card drift when actively editing",
      "Minimalist slate and warm paper themes with zero visual clutter"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/zero-g-notes.git\ncd zero-g-notes && npm install && npm start",
    githubUrl: "https://github.com/IlhamXkyo/zero-g-notes",
    liveUrl: null,
    topics: ["electron", "desktop-app", "notes", "minimalism", "productivity"],
    featured: false
  },
  {
    id: "codemask",
    name: "codemask",
    category: "tools",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-05",
    tagline: "Zero-Dependency Syntax-Preserving Secret Masking for LLM Workflows",
    description: "Zero-dependency CLI for bidirectional, syntax-preserving secret masking in LLM code workflows and agent prompts.",
    architecture: "Bidirectional AST-aware regex tokenizer that detects API keys, tokens, database URIs, and credentials, replacing them with syntax-compliant dummy identifiers. Stores encrypted mapping in local memory session, restoring real secrets automatically upon receiving LLM response.",
    highlights: [
      "Preserves code syntax so LLM-generated code compiles without errors",
      "Bidirectional: mask on prompt egress, unmask on patch ingress",
      "Zero external runtime dependencies for maximum security auditability",
      "Encrypted ephemeral local session state"
    ],
    cliSnippet: "cat src/config.ts | npx codemask mask > prompt.txt",
    githubUrl: "https://github.com/IlhamXkyo/codemask",
    liveUrl: null,
    topics: ["ai-agents", "cli", "code-privacy", "developer-tools", "llm-security", "zero-dependencies"],
    featured: true
  },
  {
    id: "warga-os",
    name: "warga-os",
    category: "civic",
    language: "TypeScript",
    langColor: "#3178c6",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-04",
    tagline: "Super-App Solusi Masalah Nyata Sehari-hari Warga & Anak Kos Indonesia",
    description: "Super-App solusi masalah nyata keseharian warga & anak kos Indonesia: Generator Surat Resmi A4/PDF, Simulator Token Listrik PLN, Navigator Birokrasi Anti-Pungli, Pantri Tropis, & Tanggap Darurat.",
    architecture: "Client-side offline-first TypeScript architecture with print-calibrated CSS paged media engine. Computes precise PLN electricity consumption profiles based on official ESDM tariff tables and provides structured legal document templates.",
    highlights: [
      "100% offline, privacy-first, zero ads, zero fees",
      "Generator Surat Resmi A4 baku (Pengantar RT/RW, SKU, Kuasa, Sewa Kos)",
      "Simulator daya listrik PLN dengan kalkulasi sisa hari token",
      "Navigator hak birokrasi kependudukan anti-pungli berdasar UU No. 24/2013"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/warga-os.git",
    githubUrl: "https://github.com/IlhamXkyo/warga-os",
    liveUrl: null,
    topics: ["typescript", "civic-tech", "indonesia", "offline-first", "utility", "open-source"],
    featured: true
  },
  {
    id: "cadence-forge",
    name: "cadence-forge",
    category: "nlp",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-27",
    tagline: "Prose Rhythm Sculptor, Sentence DNA Breaker, & Anti-Slop Workbench",
    description: "Prose Rhythm Sculptor, Sentence DNA Breaker, and Anti-Slop Rewriting Workbench designed to dismantle monotone AI text rhythms.",
    architecture: "Rhythmic sentence metric parser that deconstructs prose into visual syllable barcodes and word-count distributions to identify and break artificial monotony.",
    highlights: [
      "Sentence DNA ribbon displaying rhythmic beat variation",
      "Monotony warning engine flagging uniform sentence structures",
      "Cadence variance score and micro-restructuring guidance",
      "Zero server calls; runs entirely client-side"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/cadence-forge.git",
    githubUrl: "https://github.com/IlhamXkyo/cadence-forge",
    liveUrl: null,
    topics: ["nlp", "prose-rhythm", "stylometrics", "anti-slop", "writing-tools"],
    featured: false
  },
  {
    id: "aurum-ai-terminal",
    name: "aurum-ai-terminal",
    category: "quant",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Institutional-Grade Gold & Forex Live Terminal with Multi-Agent SMC Mapping",
    description: "Institutional-grade Gold & Forex live terminal featuring concurrent multi-agent intelligence, SMC liquidity mapping, and real-time tick streams.",
    architecture: "Asynchronous Python pipeline with concurrent agent reasoning threads. Detects Fair Value Gaps (FVG), order blocks, and liquidity pools using Smart Money Concepts (SMC), streaming live market telemetry via WebSockets.",
    highlights: [
      "Smart Money Concept (SMC) order block & liquidity pool mapping",
      "Concurrent adversarial multi-agent market debate consensus",
      "High-throughput tick stream parsing and statistical volatility bands",
      "Institutional dark terminal interface with ANSI telemetry"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/aurum-ai-terminal.git",
    githubUrl: "https://github.com/IlhamXkyo/aurum-ai-terminal",
    liveUrl: null,
    topics: ["python", "algorithmic-trading", "forex", "gold-trading", "smc", "terminal"],
    featured: true
  },
  {
    id: "agent-pulse",
    name: "agent-pulse",
    category: "tools",
    language: "TypeScript",
    langColor: "#3178c6",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Autonomous AI Agent Observability & Tracing Waterfall Studio",
    description: "Next-Gen Autonomous AI Agent Observability, Tracing Waterfall & Interactive Playground Studio.",
    architecture: "Structured observability studio tracking agent execution DAGs, tool call latency breakdowns, token burn telemetry, and step-by-step reasoning replay.",
    highlights: [
      "Interactive execution waterfall timeline",
      "Tool invocation inspection with input/output diffs",
      "Token budget depletion and prompt latency metrics",
      "Interactive scenario simulation sandbox"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/agent-pulse.git",
    githubUrl: "https://github.com/IlhamXkyo/agent-pulse",
    liveUrl: null,
    topics: ["typescript", "ai-agents", "observability", "tracing", "developer-tools"],
    featured: false
  },
  {
    id: "comic-voice-reader",
    name: "comic-voice-reader",
    category: "quant",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-05",
    tagline: "Automated Comic Screen Reader with Comic-Book Visual Styling",
    description: "Aplikasi pembaca layar komik otomatis dengan gaya visual buku komik, pengawas gulir pintar, dan suara instan.",
    architecture: "Python computer vision pipeline detecting speech bubbles and comic panels in real-time, executing localized OCR, and generating expressive voice synthesis synchronized with user scrolling.",
    highlights: [
      "Smart viewport scroll tracking for panel-by-panel reading",
      "Localized speech bubble segmentation and text extraction",
      "Instant expressive speech synthesis",
      "Visual manga comic reader overlay"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/comic-voice-reader.git",
    githubUrl: "https://github.com/IlhamXkyo/comic-voice-reader",
    liveUrl: null,
    topics: ["python", "ocr", "speech-synthesis", "comic-reader", "computer-vision"],
    featured: false
  },
  {
    id: "PegRogue",
    name: "PegRogue",
    category: "games",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Arcade Pachinko Roguelike & Relic Deckbuilder",
    description: "Arcade Pachinko Roguelike & Relic Deckbuilder combining Peglin & Balatro mechanics.",
    architecture: "Pure JavaScript Canvas 2D engine handling peg ball collisions, trajectory prediction, and complex relic multiplier synergies with turn-based progression.",
    highlights: [
      "Authentic pachinko ball bounce kinematics and elasticity calculation",
      "Modular relic synergy engine with exponential score multipliers",
      "Procedural dungeon map progression and enemy boss scaling",
      "Zero framework overhead, pure Canvas 2D performance"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/PegRogue.git",
    githubUrl: "https://github.com/IlhamXkyo/PegRogue",
    liveUrl: null,
    topics: ["gamedev", "arcade", "roguelike", "deckbuilder", "canvas-game"],
    featured: false
  },
  {
    id: "NeonDrift",
    name: "NeonDrift",
    category: "games",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "3D Arcade Midnight Expressway Drifter & Traffic Dodger",
    description: "3D Arcade Midnight Expressway Drifter & Traffic Dodger built with Three.js and Web Audio API.",
    architecture: "Procedural infinite expressway generator with curved road meshes, vehicle kinematic collision handling, and procedural audio synthesis for engine revving and tire screeching.",
    highlights: [
      "Procedural curving highway generation with dynamic traffic AI",
      "Car drift momentum and lateral slip kinematics",
      "Procedural sound synthesis (synthesized engine harmonics and tire screech)",
      "Dynamic headlights and reflective road wetness shaders"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/NeonDrift.git",
    githubUrl: "https://github.com/IlhamXkyo/NeonDrift",
    liveUrl: null,
    topics: ["threejs", "webgl", "arcade-game", "racing", "web-audio", "procedural"],
    featured: false
  },
  {
    id: "prose-sentinel",
    name: "prose-sentinel",
    category: "nlp",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-04",
    tagline: "CLI Prose Style Anomaly Analysis & Editorial Linter",
    description: "CLI prose style anomaly analysis and editorial linting tool. Not an AI detector, but a precision stylistic workbench.",
    architecture: "Python command-line tool measuring lexical diversity (Type-Token Ratio, Hapax Legomena), syntactic symmetry, and distribution anomalies across technical and prose manuscripts.",
    highlights: [
      "Statistical lexical dispersion and vocabulary entropy telemetry",
      "Zero cloud reliance; runs 100% locally on terminal stdin/files",
      "Identifies monotonous sentence length clusters",
      "Colorized terminal ANSI inspection report"
    ],
    cliSnippet: "python -m prose_sentinel document.txt",
    githubUrl: "https://github.com/IlhamXkyo/prose-sentinel",
    liveUrl: null,
    topics: ["python", "cli", "stylometrics", "text-analysis", "writing-tools"],
    featured: false
  },
  {
    id: "roblox-store-task",
    name: "roblox-store-task",
    category: "civic",
    language: "PHP",
    langColor: "#4F5D95",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Roblox E-Commerce Platform with Full Order Lifecycle",
    description: "Roblox Store: Sistem E-Commerce Item Roblox berbasis Web (PHP Native, MySQL, Bootstrap 5) dengan Autentikasi, Katalog, Tracking, dan Dashboard Admin.",
    architecture: "Fullstack PHP Native architecture with relational MySQL database. Implements secure role-based authentication (Admin/Buyer), product catalog, order status tracking (Packed to Completed), and comprehensive administrative CRUD.",
    highlights: [
      "Role-based access control with session security",
      "End-to-end checkout flow with item order tracking",
      "Administrative dashboard for category, product, and customer management",
      "Clean relational schema with SQL transaction safety"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/roblox-store-task.git",
    githubUrl: "https://github.com/IlhamXkyo/roblox-store-task",
    liveUrl: null,
    topics: ["php", "mysql", "ecommerce", "web-development", "fullstack"],
    featured: false
  },
  {
    id: "custom-vton-studio",
    name: "custom-vton-studio",
    category: "quant",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Generative AI Studio for Virtual Try-On, Inpainting & Background Replacement",
    description: "Custom Generative AI Studio for Virtual Try-On, Inpainting, and Background Replacement.",
    architecture: "Python PyTorch pipeline leveraging diffusion-based garment warping, semantic body segmentation, and inpainting models to seamlessly blend clothing onto human subjects.",
    highlights: [
      "Garment geometric deformation and warping alignment",
      "Semantic human parsing (dense pose and skin boundary detection)",
      "Local GPU accelerated inference pipeline",
      "Interactive canvas mask editor for manual seam refinement"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/custom-vton-studio.git",
    githubUrl: "https://github.com/IlhamXkyo/custom-vton-studio",
    liveUrl: null,
    topics: ["python", "pytorch", "generative-ai", "virtual-try-on", "inpainting"],
    featured: false
  },
  {
    id: "TrackingHand",
    name: "TrackingHand",
    category: "quant",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Real-time Spatial Computer Vision Hand Tracking",
    description: "Real-time computer vision hand tracking and spatial landmark vector calculation.",
    architecture: "OpenCV and MediaPipe vision pipeline calculating 21 3D hand landmarks in real time with finger flexion angle analysis and gesture state classification.",
    highlights: [
      "21-point 3D skeletal landmark tracking at 30+ FPS",
      "Real-time finger angle trigonometry for gesture recognition",
      "Low CPU overhead OpenCV frame capture",
      "Modular hook for spatial UI and robotic control"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/TrackingHand.git",
    githubUrl: "https://github.com/IlhamXkyo/TrackingHand",
    liveUrl: null,
    topics: ["python", "opencv", "computer-vision", "hand-tracking", "gesture-recognition"],
    featured: false
  },
  {
    id: "App-Forum-kls-tib-stikom",
    name: "App-Forum-kls-tib-stikom",
    category: "civic",
    language: "TypeScript",
    langColor: "#3178c6",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Academic Assignment Collaboration & Coursework Discussion Platform",
    description: "Web forum diskusi tugas untuk mahasiswa Teknik Informatika STIKOM.",
    architecture: "Collaborative academic platform structuring university coursework topics, assignment submission deadlines, and student problem-solving threads.",
    highlights: [
      "Threaded course discussions categorized by academic module",
      "Assignment timeline tracking and collaborative note sharing",
      "Mobile-responsive layout optimized for university students",
      "Secure student authentication and role moderation"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/App-Forum-kls-tib-stikom.git",
    githubUrl: "https://github.com/IlhamXkyo/App-Forum-kls-tib-stikom",
    liveUrl: null,
    topics: ["typescript", "forum", "education", "collaboration", "stikom"],
    featured: false
  },
  {
    id: "forum_apk",
    name: "forum_apk",
    category: "civic",
    language: "TypeScript",
    langColor: "#3178c6",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Mobile Application Client for University Coursework Coordination",
    description: "Mobile client application for student academic forum and assignment collaboration.",
    architecture: "Cross-platform mobile client providing push notification updates on newly assigned coursework and offline cached discussion threads.",
    highlights: [
      "Offline cache for active discussion threads",
      "Push notification integration for approaching homework deadlines",
      "Fast native touch response and mobile ergonomics"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/forum_apk.git",
    githubUrl: "https://github.com/IlhamXkyo/forum_apk",
    liveUrl: null,
    topics: ["typescript", "mobile", "android", "student-tools"],
    featured: false
  },
  {
    id: "input-data-siswa",
    name: "input-data-siswa",
    category: "civic",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-01",
    tagline: "Automated Student Administrative Data Verification & Input System",
    description: "Automated student administrative record input, schema validation, and CSV export system.",
    architecture: "Python desktop automation script providing structured data entry forms with strict regex validation for national student identification numbers (NISN), gender, and academic scores.",
    highlights: [
      "Strict data type and NISN format validation",
      "Batch export to Excel/CSV with sanitized field delimiters",
      "Clear administrative GUI with rapid keyboard navigation"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/input-data-siswa.git",
    githubUrl: "https://github.com/IlhamXkyo/input-data-siswa",
    liveUrl: null,
    topics: ["python", "data-entry", "education", "desktop-tools"],
    featured: false
  },
  {
    id: "XAUUSD-Trading-Signal-simulasi",
    name: "XAUUSD-Trading-Signal-simulasi",
    category: "quant",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-04",
    tagline: "Quantitative Gold (XAU/USD) Signal Calculation & Backtesting Simulator",
    description: "Simulasi kalkulasi signal gold, dynamic trailing stop management, and historical drawdown risk assessment.",
    architecture: "Python algorithmic trading backtesting harness executing multi-timeframe moving average convergence, ATR volatility bands, and risk-to-reward ratio modeling.",
    highlights: [
      "ATR volatility-adjusted position sizing algorithm",
      "Simulated tick execution with realistic slippage modeling",
      "Maximum drawdown (MDD) and Sharpe ratio statistical reporting"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/XAUUSD-Trading-Signal-simulasi.git",
    githubUrl: "https://github.com/IlhamXkyo/XAUUSD-Trading-Signal-simulasi",
    liveUrl: null,
    topics: ["python", "quantitative-finance", "gold-trading", "backtesting", "signals"],
    featured: false
  },
  {
    id: "sentimen-forex-web",
    name: "sentimen-forex-web",
    category: "quant",
    language: "HTML",
    langColor: "#e34c26",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Forex Market Sentiment Aggregation & Live Economic Calendar",
    description: "Real-time news sentiment and technical currency pair direction indicators.",
    architecture: "Web dashboard scraping macro-economic calendar releases, central bank interest rate decisions, and retail long/short positioning ratios.",
    highlights: [
      "Real-time currency strength meter matrix",
      "Economic calendar release impact alerts",
      "Visual retail positioning heatmaps"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/sentimen-forex-web.git",
    githubUrl: "https://github.com/IlhamXkyo/sentimen-forex-web",
    liveUrl: null,
    topics: ["html", "forex", "sentiment-analysis", "financial-dashboard"],
    featured: false
  },
  {
    id: "TRSLT_RL_KYO_v1",
    name: "TRSLT_RL_KYO_v1",
    category: "quant",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Real-Time Game Voice Translator & Audio Encryption Bridge",
    description: "Enskrip audio to text and translate it in rl for any people meet in hangout game.",
    architecture: "Low-latency audio streaming pipeline capturing desktop game voice communication, transcribing speech to text, encrypting audio payloads, and translating cross-language messages in real time.",
    highlights: [
      "Direct microphone and loopback audio stream capture",
      "Low-latency speech-to-text with auto-language detection",
      "In-game text overlay integration for multiplayer games",
      "End-to-end encrypted packet transmission"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/TRSLT_RL_KYO_v1.git",
    githubUrl: "https://github.com/IlhamXkyo/TRSLT_RL_KYO_v1",
    liveUrl: null,
    topics: ["python", "speech-to-text", "translation", "real-time", "gaming"],
    featured: false
  },
  {
    id: "chiikawa-runner",
    name: "chiikawa-runner",
    category: "games",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "2D Arcade Parallax Runner with Responsive Controls",
    description: "Fast-paced arcade 2D endless runner featuring dynamic parallax obstacles and responsive jumping mechanics.",
    architecture: "HTML5 Canvas game loop utilizing variable timestep kinematics, state machine character animations, and procedural obstacle spawning.",
    highlights: [
      "Sub-pixel smooth canvas rendering loop",
      "Dynamic obstacle spacing based on running velocity",
      "Multi-layered parallax background scrolling",
      "Mobile touch and desktop keyboard binding"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/chiikawa-runner.git",
    githubUrl: "https://github.com/IlhamXkyo/chiikawa-runner",
    liveUrl: null,
    topics: ["javascript", "canvas-game", "runner", "arcade", "gamedev"],
    featured: false
  },
  {
    id: "neon-calculator",
    name: "neon-calculator",
    category: "tools",
    language: "CSS",
    langColor: "#563d7c",
    stars: 0,
    forks: 0,
    updatedAt: "2026-09-23",
    tagline: "Tactile Precision Calculator with Mechanical Tactile Feedback",
    description: "Precision tactile calculator featuring bespoke button depression states and optical styling.",
    architecture: "Pure CSS and vanilla JS calculator implementing arithmetic parser with operator precedence and physical mechanical button depression states.",
    highlights: [
      "Subtle optical styling and mechanical keypress states",
      "Full keyboard numpad support and calculation history",
      "Precision decimal arithmetic rounding"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/neon-calculator.git",
    githubUrl: "https://github.com/IlhamXkyo/neon-calculator",
    liveUrl: null,
    topics: ["css", "calculator", "ui-design", "frontend"],
    featured: false
  },
  {
    id: "Androrat",
    name: "Androrat",
    category: "tools",
    language: "Python",
    langColor: "#3572A5",
    stars: 0,
    forks: 0,
    updatedAt: "2026-05-16",
    tagline: "Client-Server Socket Telemetry & Remote System Diagnostics",
    description: "Remote administration and socket diagnostic tool utilizing Java client and Python server architecture.",
    architecture: "Dual-layer socket communication architecture coordinating TCP command payloads, remote sensor telemetry, and connection heartbeat monitoring.",
    highlights: [
      "Asynchronous socket message dispatching",
      "System resource and network state telemetry",
      "Resilient socket reconnection handler"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/Androrat.git",
    githubUrl: "https://github.com/IlhamXkyo/Androrat",
    liveUrl: null,
    topics: ["python", "java", "sockets", "networking", "telemetry"],
    featured: false
  },
  {
    id: "IlhamXkyo",
    name: "IlhamXkyo",
    category: "tools",
    language: "Markdown",
    langColor: "#083fa1",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-04",
    tagline: "Core Developer Identity & Open Source Portfolio Profile",
    description: "Official GitHub developer identity, configuration matrix, and open source documentation repository.",
    architecture: "Centralized configuration metadata documenting engineering values, repository catalogs, and contact credentials for Ilham.",
    highlights: [
      "Developer manifesto and active focus areas",
      "Dynamic activity feeds and open source credentials",
      "Verification links and public key information"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/IlhamXkyo.git",
    githubUrl: "https://github.com/IlhamXkyo/IlhamXkyo",
    liveUrl: null,
    topics: ["github-profile", "portfolio", "documentation", "identity"],
    featured: false
  },
  {
    id: "aeroflow-lab",
    name: "aeroflow-lab",
    category: "tools",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-08",
    tagline: "Aerodynamic Wind Tunnel & Fluid Vortex Telemetry Simulator",
    description: "Interactive aerodynamic wind tunnel, Eulerian Navier-Stokes fluid telemetry, and acoustic vortex shedding simulator.",
    architecture: "Eulerian grid-based Navier-Stokes fluid solver executing real-time velocity advection, pressure Poisson Jacobi relaxation, obstacle boundary projection, and particle streakline rendering.",
    highlights: [
      "Eulerian Navier-Stokes grid solver with velocity advection",
      "Real-time obstacle boundary projection and drag analysis",
      "Vortex shedding telemetry and acoustic frequency mapping",
      "Interactive wind tunnel velocity and obstacle controls"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/aeroflow-lab.git",
    githubUrl: "https://github.com/IlhamXkyo/aeroflow-lab",
    liveUrl: null,
    topics: ["fluid-dynamics", "physics-simulation", "navier-stokes", "canvas", "interactive-tools"],
    featured: false
  },
  {
    id: "torsion-lab",
    name: "torsion-lab",
    category: "tools",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-08",
    tagline: "Kinetic Chaos Laboratory & Vector Phase Space Telemetry",
    description: "Interactive kinetic chaos laboratory, vector phase space telemetry, and procedural acoustic resonance workbench.",
    architecture: "Symplectic Verlet integrator modeling non-linear coupled pendulums, Poincare surface of section mapping, Lyapunov exponent estimation, and real-time phase space orbit trajectory projection.",
    highlights: [
      "Symplectic Verlet physics numerical integration",
      "Poincare phase space section mapping",
      "Lyapunov exponent divergence estimation",
      "Harmonic resonance audio feedback"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/torsion-lab.git",
    githubUrl: "https://github.com/IlhamXkyo/torsion-lab",
    liveUrl: null,
    topics: ["physics", "chaos-theory", "simulation", "interactive", "web-audio"],
    featured: false
  },
  {
    id: "BioGenesis",
    name: "BioGenesis",
    category: "quant",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-08",
    tagline: "Emergent Artificial Life & Primordial Particle Chemistry",
    description: "Interactive emergent artificial life and primordial particle chemistry sandbox built with HTML5 Canvas and Web Audio API.",
    architecture: "Spatial grid hashing algorithm partitioning thousands of interacting particle species with asymmetric attraction-repulsion force kernels, simulating primordial cellular clustering and self-organizing motility.",
    highlights: [
      "Spatial partition grid indexing for O(N) neighbor interaction",
      "Multi-species asymmetric attraction-repulsion kernels",
      "Real-time population entropy and clustering telemetry",
      "Zero external physics libraries"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/BioGenesis.git",
    githubUrl: "https://github.com/IlhamXkyo/BioGenesis",
    liveUrl: null,
    topics: ["artificial-life", "emergence", "particle-simulation", "canvas", "web-audio"],
    featured: false
  },
  {
    id: "AetherPulse",
    name: "AetherPulse",
    category: "quant",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-08",
    tagline: "Generative Particle Symphony & Spatial Audio Sandbox",
    description: "Interactive 3D generative particle symphony and procedural spatial audio sandbox built with Three.js and Web Audio API.",
    architecture: "GPU-accelerated vertex shader particle system coupled to a Web Audio procedural synthesizer node graph, translating 3D particle kinematics and collision impulses into harmonic polyphonic spatial sound.",
    highlights: [
      "GPU particle kinematic simulation with custom vertex shaders",
      "Web Audio API procedural sound synthesis nodes",
      "Binaural spatial panner nodes mapped to camera distance",
      "Zero audio assets (100% procedural waveform generation)"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/AetherPulse.git",
    githubUrl: "https://github.com/IlhamXkyo/AetherPulse",
    liveUrl: null,
    topics: ["threejs", "web-audio", "generative-art", "particles", "spatial-audio"],
    featured: false
  },
  {
    id: "IlhamXkyo.github.io",
    name: "IlhamXkyo.github.io",
    category: "tools",
    language: "JavaScript",
    langColor: "#f7df1e",
    stars: 0,
    forks: 0,
    updatedAt: "2026-10-08",
    tagline: "Personal Engineering Lab & High-Density Workstation Portfolio",
    description: "Personal engineering workstation portfolio with live interactive workbenches, zero-dependency CLI tooling, and responsive case studies.",
    architecture: "Zero-build modular ES6 architecture. Native CSS custom properties token system, Web Audio synthesizer, canvas particle physics, and zero external runtime dependencies.",
    highlights: [
      "Zero runtime framework dependencies (vanilla web platform)",
      "3 interactive developer workbenches (CodeMask, Portwarden, Slop-Lens)",
      "Procedural Web Audio acoustic feedback engine",
      "Integrated UNIX developer shell with autocomplete"
    ],
    cliSnippet: "git clone https://github.com/IlhamXkyo/IlhamXkyo.github.io.git\nnpm start",
    githubUrl: "https://github.com/IlhamXkyo/IlhamXkyo.github.io",
    liveUrl: "https://ilhamxkyo.github.io",
    topics: ["portfolio", "developer-tools", "vanilla-js", "web-audio", "case-studies"],
    featured: false
  }
];
